version: '3.8'

services:
  db:
    image: postgres
    container_name: shamiri-backend-database
    environment:
      POSTGRES_DB: shamiridb
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: PasswordSecret
    ports:
      - "5432:5432"
  test_db:
    image: postgres
    container_name: shamiri-backend-test-database
    environment:
      POSTGRES_DB: test_shamiridb  
      POSTGRES_USER: test_user      
      POSTGRES_PASSWORD: TestPassword  
    ports:
      - "5433:5433" 
  web:
    build: .
    image: shamiri-app-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  migrate:
    build: .
    command: >
      sh -c "alembic revision --autogenerate -m 'Create user and journal tables' &&
             alembic upgrade head"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://app_user:PasswordSecret@db:5432/shamiridb

  test:
    build: .
    command: ["pytest", "--disable-warnings"]
    volumes:
      - .:/app
    depends_on:
      - test_db
