version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: shamiridb
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: PasswordSecret
    ports:
      - "5432:5432"
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://app_user:PasswordSecret@db:5432/shamiridb
