"""Create user and journal tables

Revision ID: 04c2cdaa5564
Revises: c2ce0c94802e
Create Date: 2024-07-11 06:05:41.848101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c2cdaa5564'
down_revision: Union[str, None] = 'c2ce0c94802e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
