"""Create user and journal tables

Revision ID: 14f8128e91d1
Revises: 4bd9ca5d7be9
Create Date: 2024-07-11 07:57:40.432877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f8128e91d1'
down_revision: Union[str, None] = '4bd9ca5d7be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
