"""Create user and journal tables

Revision ID: 6ec3d3cd1679
Revises: da8abb0da2f5
Create Date: 2024-07-11 05:53:50.642028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec3d3cd1679'
down_revision: Union[str, None] = 'da8abb0da2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
