"""Create user and journal tables

Revision ID: 80618c057e5b
Revises: 6ec3d3cd1679
Create Date: 2024-07-11 05:56:47.890096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80618c057e5b'
down_revision: Union[str, None] = '6ec3d3cd1679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
