"""Create user and journal tables

Revision ID: 81446f9a8ddd
Revises: 4aac43ed437e
Create Date: 2024-07-11 05:19:19.602788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81446f9a8ddd'
down_revision: Union[str, None] = '4aac43ed437e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
