"""Create user and journal tables

Revision ID: 8b14ffccb8b5
Revises: a775093a0c1f
Create Date: 2024-07-11 06:46:00.937794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b14ffccb8b5'
down_revision: Union[str, None] = 'a775093a0c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
