"""Create user and journal tables

Revision ID: ee28b42d7cdc
Revises: 01dc5b6a7157
Create Date: 2024-07-11 07:27:46.708917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee28b42d7cdc'
down_revision: Union[str, None] = '01dc5b6a7157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
